### ISSUE TITLE
change configuration to array

### ISSUE THREAD

**Issue by gentoomaniac** [gentoomaniac/minigal-nano-ng#9]
Change the config* files to have a $CONFIG[] array instead which can be easily spotted in other files

**Comment by Shulyaka** [comment]
Hi Marco,

Since you're going to rewrite configuration, please let me add my 2 cents, if I may:
1. "small" and "original" links are not localizable. Would be good to add localization string parameters for them
2. consider removing config.php (which is a custom configuration file) out of git control. A system_check or readme could suggest to create one by copying fromconfig_default.php. I'm not sure how good this idea is, this is just a thought.

**Comment by gentoomaniac** [comment]
1. Was actually thinking already about localization options. Guess it will eb on the ToDo list then.

2. This is a part of the original code. probably move everything in a config.php.default which then needs to be moved to config.php (like other projects do)
I like the idea of then adding it to the system_check
